### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by openmac** [JoaoFelipe/rakuen-translation#2]
I believe a few months ago I was able to use this, but now when trying to extract the text from the game it gives out this error:
`extractor.rb:547:in `block in process_map': undefined method `to_h' for #<Array:0x007fcec0010c48> (NoMethodError)
	from extractor.rb:545:in `open'
	from extractor.rb:545:in `process_map'
	from extractor.rb:578:in `block in process_maps'
	from extractor.rb:576:in `each'
	from extractor.rb:576:in `process_maps'
	from extractor.rb:586:in `process_events'
	from extractor.rb:859:in `extract_text'
	from extractor.rb:911:in `block in <main>'
	from extractor.rb:910:in `open'
	from extractor.rb:910:in `<main>'`

**Comment by JoaoFelipe** [comment]
Thank you for reporting the issue, I'll look into it

**Comment by openmac** [comment]
Thanks.

**Comment by JoaoFelipe** [comment]
I couldn't reproduce.
Are you trying to extract from the latest version of the game without any modifications?

What is the version of your ruby? Here I'm using 2.3.3p222 64bit.

**Comment by openmac** [comment]
Ah, thank you very much, it was a matter of having an older version of Ruby (2.0) installed on my machine, by installing Ruby 2.3.x I was able to use extractor.rb.
