### ISSUE TITLE
Got an error when debug mode is enabled

### ISSUE THREAD

**Issue by izayoi256** [JoaoFelipe/rakuen-translation#3]
Windows 10 64bit

Enabled debug mode and launched the game. I got an error below when I selected "New Story" at the title screen.

---------------------------
Rakuen
---------------------------
Script 'Game_Temp' line 0: LoadError occurred.

No such file to load -- C:/Program Files (x86)/Steam/steamapps/common/Rakuen/Data/mods.rb
---------------------------
OK   
---------------------------

Do you have any idea?

**Comment by JoaoFelipe** [comment]
Does this occur only in debug mode?

Is mods.rb in this directory? (C:/Program Files (x86)/Steam/steamapps/common/Rakuen/Data/mods.rb)

**Comment by izayoi256** [comment]
> Does this occur only in debug mode?

Yeah, I got this only while I uncommented ```#load("#{path}/debug.rb")```. 

> Is mods.rb in this directory?

No. Here is the contents of it.

```
PS C:\Program Files (x86)\Steam\steamapps\common\Rakuen\Data> dir


    ディレクトリ: C:\Program Files (x86)\Steam\steamapps\common\Rakuen\Data


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2020/04/16     20:10                mods
-a----       2020/04/16     20:10         186972 Scripts.rxdata
```

**Comment by JoaoFelipe** [comment]
I see. Can you try to change the following line:
https://github.com/JoaoFelipe/rakuen-translation/blob/master/mods.rb#L42
to
` load("#{$Dir.getwd}/mods.rb")`

I think I moved the mod system to the Data folder after finishing the translation, forgot to change this path and didn't activate the debug mode after. I can't test it right now, since the game is not installed and I'm busy with other things

**Comment by izayoi256** [comment]
It worked well on the other machine Linux Mint. Will try on windows 10 later. I'll close the issue and make PR if it works well too.

**Comment by izayoi256** [comment]
That worked on windows 10, so I made a PR for this problem. thanks for your helping.
